#!/bin/bash
recipient=$1

# check recipient
if [ -z "$1" ]
  then
    echo "No recipient provided"
    exit 1
fi

# send
echo "Sending all tokens to $recipient..."

count = 0

while read -r account;
do 
    if (( "$count" >= 2 )); then
        mint="${account%% *}"
        amountUtr="${account#* }"
        amount=`echo $amountUtr | sed 's/ *$//g'`
        if ! [ -z "$amount" ] && (( $(echo "$amount > 0" |bc -l) )); then
            echo "Sending $amount $mint to $recipient..."
            spl-token transfer --fund-recipient $mint $amount $recipient
            echo "----" 
        fi
    fi
    (( count++ ))
done < <(spl-token accounts) 
